apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mysql
  namespace: db
spec:
  interval: 30m
  chart:
    spec:
      chart: mysql
      version: "10.1.1"  # 더 안정적인 버전
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      rootPassword: "SuperSecretRootPassword123!"
      database: "cryptopedia"
      username: "cryptopedia"
      password: "CryptopediaUserPassword456!"
    primary:
      persistence:
        enabled: true
        storageClass: "longhorn"
        size: 8Gi
    metrics:
      enabled: false  # 메트릭 비활성화로 단순화
