apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
  namespace: db
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      version: "19.6.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      enabled: false
    architecture: standalone
    master:
      persistence:
        enabled: true
        storageClass: "longhorn"
        size: 2Gi
    metrics:
      enabled: false
