apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
  namespace: db
spec:
  interval: 30m
  timeout: 15m
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    disableWait: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: redis
      version: "19.6.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: bitnamilegacy/redis
    auth:
      enabled: false
    architecture: standalone
    master:
      persistence:
        enabled: true
        storageClass: "longhorn"
        size: 2Gi
    metrics:
      enabled: false
