apiVersion: ENC[AES256_GCM,data:ZOc=,iv:AmVhNfR3pb2ke0TQeGTKcj7czBItMpt/Cc2/cdLjUBQ=,tag:tI/v6pd+eEVF6Rb7fejlWQ==,type:str]
kind: ENC[AES256_GCM,data:r3cJRpza,iv:oO3KQcFa8dvyphst4Q8AAZ1XqfjQyhgP7HiuRwHwgEg=,tag:xWjACBNAd80lo04gr9AfcQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YxsUdVRGaDM92wo=,iv:9bduGNHApgLm4V7FUq5rV/SA7AOgWXsVwHIQVHoGuoU=,tag:KoKwD6wFsEMiy6QqEG+Dtw==,type:str]
    namespace: ENC[AES256_GCM,data:JrdHXn1l6pwPsnk=,iv:sifS254dcC/8vYsYUyKrN+BmpjK9jQJlTPYMQwQ7bjs=,tag:7ZMRFEFBXZLPD7XBVU4Hbg==,type:str]
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:K2kjEeVtMyrxvXZRdtAWu9XK+onPr976VenhLqG/Jr4l0STWvQEnTniRoFjHLFFSG/tafROF+TwCFnVhF+OR2VC/jBbZK2PkcL1WppZb/bmeGwYekjXf2p4ja1RRiVj005Y3rKdrc7uC/d+JtBwUK+VcW0cGvArbcXyGYJ0ap9zPVBH+FWREeq+aeXVB7hZSKtQRRhEGRA99ch/YGpp0eutIk2zTFo1w++k1/gGZjBHHyTQfy+IGpQ==,iv:Ya2VfbyHQroC0lG9e+jKktBUUl/R1SAo/kWxkF3Vzmk=,tag:qGYk9LoM6e2E5Z+YHELs3g==,type:str]
sops:
    age:
        - recipient: age19cedjkdtmz7dzzlwhvfwqukapnc37u7cqfq2dn7ttm45ej6utgnqhr6998
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicTlobWl5UlEyUHBvdEJa
            YjVsdHBaRTRqc1RVZm4vZWNuM2RHVTE4a0M0CmErdUFRWkh2U2VqdEFzNGJUQkVr
            VDBQYy9tU0JJYSt5cXpnRnVLU0V4Y1EKLS0tIDdYWEZwUnZLcE1OeHJEcElNL3Ar
            Sk0vR1JFajJRVkY1NmpsdjJKMDRIUjAKg8R58xS49fVmpOpQXY0r1NseDiTvM8lN
            igC+gXUMohGpCzXdNNKfsolbsx95VVkQ3BRvx+e+ogV4Mz+xeq2SOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-12T16:57:19Z"
    mac: ENC[AES256_GCM,data:NK9EULHZ6ftHwMjUB+maxeNrdPp/HCe4QlJHbUhuEYD1MutOWfhawLzN/Y1kSFmK1ET7NGUoXblKTUHRPWF75jhfidQPMdwd5Xxcmcv7Rpr8vSSO2Vv1THXoj6tZdXekrq09W1XMX8q9/q1tvFtXz471zmG79WutPBJ0hOQP3cE=,iv:IyzdN0P6IxTulp/xwjQ1rbqzN2HjI5q5btT+pyur3fM=,tag:NYCfHoi5Xu7xBvgctpPoaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
