apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
  namespace: observability
spec:
  interval: 30m
  timeout: 15m
  install:
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    disableWait: true
    remediation:
      retries: 3
  chart:
    spec:
      chart: promtail
      version: "6.16.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    config:
      clients:
        - url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push
      snippets:
        extraRelabelConfigs:
          - action: keep
            source_labels: [__meta_kubernetes_namespace]
            regex: (api|batch|web)
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
