apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptopedia-api
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/miner-s-life/cryptopedia-api:latest # {"$imagepolicy": "flux-system:cryptopedia-api"}
